# Generated by Django 4.1.4 on 2022-12-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airplane",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("board_num", models.CharField(max_length=10, unique=True)),
                ("passengers", models.IntegerField()),
                ("fuel_tank", models.IntegerField()),
                (
                    "consumption_per_minute",
                    models.DecimalField(decimal_places=5, max_digits=7),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
            ],
        ),
    ]
