# Generated by Django 4.1.4 on 2022-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airplane",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("board_num", models.CharField(max_length=10, unique=True)),
                ("passengers", models.IntegerField()),
                ("fuel_tank", models.IntegerField(blank=True)),
                (
                    "consumption_per_minute",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7
                    ),
                ),
                (
                    "minutes_to_fly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
    ]
