# Generated by Django 4.1.4 on 2022-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airplanes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name"], "verbose_name_plural": "companies"},
        ),
        migrations.AlterField(
            model_name="airplane",
            name="consumption_per_minute",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="fuel_tank",
            field=models.IntegerField(blank=True),
        ),
    ]
